### ISSUE TITLE
Considering jnius for the jni communication

### ISSUE THREAD

**Issue by AbdealiLoKo** [jpmml/jpmml-evaluator-python#1]
The major difference between py4j and jnius is that py4j does a network socket based communication with it's own gateway server. While jnius does JNI communication with a JVM.

A while back I had the same usecase of running PMMLs in python, and evaluated them both. Redid the evaluation when I saw this library:
```python
from jpmml_evaluator import launch_gateway, _package_classpath
from jpmml_evaluator import Evaluator, LoadingModelEvaluatorBuilder

import jnius_config
jnius_config.set_classpath(*_package_classpath())

py4j_gateway = None
py4j_evaluator = None
jnius_evaluator = None


def py4j_createjvm():
    global py4j_gateway
    if py4j_gateway is None:
        py4j_gateway = launch_gateway()

def py4j_loadmodel():
    global py4j_evaluator
    evaluatorBuilder = LoadingModelEvaluatorBuilder(py4j_gateway) \
        .setLocatable(True) \
        .loadFile("jpmml_evaluator/tests/resources/DecisionTreeIris.pmml")

    py4j_evaluator = evaluatorBuilder.build().verify()

def py4j_fieldquery():
    inputFields = py4j_evaluator.getInputFields()
    vals = [inputField.getName() for inputField in inputFields]
    # print("Input fields: ", vals)

    targetFields = py4j_evaluator.getTargetFields()
    vals = [targetField.getName() for targetField in targetFields]
    # print("Target field(s): ", vals)

    outputFields = py4j_evaluator.getOutputFields()
    vals = [outputField.getName() for outputField in outputFields]
    # print("Output fields: ", vals)

def py4j_score(val=0):
    arguments = {
        "Sepal_Length" : 5.1 + val,
        "Sepal_Width" : 3.5 + val,
        "Petal_Length" : 1.4 + val,
        "Petal_Width" : 0.2 + val,
    }

    results = py4j_evaluator.evaluate(arguments)
    # print(results)


def jnius_createjvm():
    import jnius

def jnius_loadmodel():
    global jnius_evaluator
    import jnius
    jLoadingModelEvaluatorBuilder = jnius.autoclass("org.jpmml.evaluator.LoadingModelEvaluatorBuilder")
    jFile = jnius.autoclass('java.io.File')
    jString = jnius.autoclass("java.lang.String")

    evaluatorBuilder = jLoadingModelEvaluatorBuilder()
    evaluatorBuilder.setLocatable(True)
    evaluatorBuilder.load(jFile(jString("jpmml_evaluator/tests/resources/DecisionTreeIris.pmml")))
    jnius_evaluator = evaluatorBuilder.build()

def jnius_fieldquery():
    import jnius
    inputFields = jnius_evaluator.getInputFields()
    vals = [inputFields.get(i).getName().getValue() for i in range(inputFields.size())]
    # print("Input fields: ", vals)

    targetFields = jnius_evaluator.getTargetFields()
    vals = [targetFields.get(i).getName().getValue() for i in range(targetFields.size())]
    # print("Target field(s): ", vals)

    outputFields = jnius_evaluator.getOutputFields()
    vals = [outputFields.get(i).getName().getValue() for i in range(outputFields.size())]
    # print("Output fields: ", vals)

def jnius_score(val=0):
    import jnius
    jModelEvaluationContext = jnius.autoclass('org.jpmml.evaluator.ModelEvaluationContext')
    jEvaluatorUtil = jnius.autoclass("org.jpmml.evaluator.EvaluatorUtil")
    jDouble = jnius.autoclass('java.lang.Double')
    jString = jnius.autoclass("java.lang.String")

    arguments = {
        "Sepal_Length" : 5.1 + val,
        "Sepal_Width" : 3.5 + val,
        "Petal_Length" : 1.4 + val,
        "Petal_Width" : 0.2 + val,
    }

    model_inputs = jModelEvaluationContext(jnius_evaluator)

    input_fields = jnius_evaluator.getInputFields()
    for i in range(input_fields.size()):
        field_name = input_fields.get(i).getName()
        model_inputs.declare(field_name, jDouble(arguments[field_name.getValue()]))

    results1 = jnius_evaluator.evaluate(model_inputs)
    results2 = jEvaluatorUtil.decode(results1)
    results = {k: results2.get(jString(k)) for k in results2.keySet().toArray()}
    # print(results)

```

### Create JVM
```
In [2]: %time py4j_createjvm()
CPU times: user 2.2 ms, sys: 6.49 ms, total: 8.7 ms
Wall time: 180 ms

In [3]: %time jnius_createjvm()
CPU times: user 70.3 ms, sys: 22.6 ms, total: 92.9 ms
Wall time: 93.9 ms
```
**Conclusion**: In JVM creation, py4j is slower than jnius. (As this is one time activity - this is not too important)

### Load Model
```
In [5]: %time py4j_loadmodel()
CPU times: user 5.39 ms, sys: 3.48 ms, total: 8.87 ms
Wall time: 1.04 s

In [6]: %timeit py4j_loadmodel()
2.82 ms ± 627 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [7]: %time jnius_loadmodel()
CPU times: user 3.86 s, sys: 196 ms, total: 4.06 s
Wall time: 1.45 s

In [8]: %timeit jnius_loadmodel()
1.03 ms ± 226 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
**Conclusion**: py4j is slower than jnius on the loading part

### Field Queries
```
In [9]: %time py4j_fieldquery()
CPU times: user 4.6 ms, sys: 2.51 ms, total: 7.1 ms
Wall time: 17 ms

In [10]: %timeit py4j_fieldquery()
3.52 µs ± 352 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [11]: %time jnius_fieldquery()
CPU times: user 9.85 ms, sys: 1.3 ms, total: 11.1 ms
Wall time: 8.27 ms

In [12]: %timeit jnius_fieldquery()
217 µs ± 9.66 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
**Conclusion**: jnius is faster on the first load, but py4j is faster for subsequent runs of the same.

### Scoring
```
In [13]: %time py4j_score()
CPU times: user 6.97 ms, sys: 3.67 ms, total: 10.6 ms
Wall time: 77.9 ms

In [14]: %timeit py4j_score()
4.15 ms ± 589 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [15]: %time jnius_score()
CPU times: user 93 ms, sys: 4.61 ms, total: 97.6 ms
Wall time: 72.5 ms

In [16]: %timeit jnius_score()
527 µs ± 12.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [22]: val = 0.3
    ...: %time py4j_score(val)
    ...: %time jnius_score(val)
    ...:
CPU times: user 1.93 ms, sys: 1.33 ms, total: 3.26 ms
Wall time: 6.35 ms
CPU times: user 1.02 ms, sys: 40 µs, total: 1.06 ms
Wall time: 1.05 ms

In [23]: val = 0.4
    ...: %time py4j_score(val)
    ...: %time jnius_score(val)
    ...:
CPU times: user 1.87 ms, sys: 1.13 ms, total: 3 ms
Wall time: 5 ms
CPU times: user 1.08 ms, sys: 570 µs, total: 1.65 ms
Wall time: 1.09 ms
```
**Conclusion**: Both py4j and jnius have similar first scoring times. But jnius tends to be 5 times faster than py4j for subsequent runs.

Notes:
 - This is just a preliminary test. The pyjnius code above is not very optimized as it runs autoclass in eery function, converts Map -> set -> array and so on. Just put it together for a rough benchmark
 - Im not sure how much time you've spend on the py4j optimization either (so not sure how optimized it is)
 - As the PMML becomes more complex, the overheads involved here would reduce probably as more time would be spent inside Java and lesser in the communication (And the java time for both would be same as they both use same libraries)
 - Jnius uses JNI and py4j uses socket, the communication with JNI is expected to be much faster.

### Impact:
PMML is typically run on batch data (bunch of records - jpmml-evaluator-python's `evaluateAll()`) or is run in a single record execution (jpmml-evaluator-python's `evaluate()`)

 - In batch evaluation: Having a 5 times slower PMML evaluator may not be a major deal unless you go towards huge data where running things on a million records can take a much longer time (jnius with 1ms/record would take ~5mins for 300k records, while py4j would take ~25mins)
 - In single evaluation: In APIs/realtime contexts every millisec is helpful

PS: This was done on 23dd82fb44552287ad856a0f6536527821f7ba7b

**Comment by vruusmann** [comment]
Thanks for a very comprehensive issue report - code examples, timings and analysis.

Now that I look at Py4J vs. (Py)jnius, then I get the idea that perhaps it's possible to introduce a helper "Java object instantiation" layer, which would make it possible to choose which backend to use? The only variable code path is object instantiation; later method invocations and field accesses seem to use identical Python code.

Py4J:
```python
javaLoadingModelEvaluatorBuilder = gateway.jvm.org.jpmml.evaluator.LoadingModelEvaluatorBuilder()
```

(Py)jnius:
```python
javaLoadingModelEvaluatorBuilder = jnius.autoclass("org.jpmml.evaluator.LoadingModelEvaluatorBuilder")
```

Overall comment about the performance - the JPMML-Evaluator should provide additional utility methods to make the preparation of input data records more compact. At the moment the body of the `Evaluator.evaluate(dict: arguments)` method looks like this:
```python
jvm = self._jvm()
javaArguments = jvm.java.util.LinkedHashMap()
for k, v in arguments.items():
	javaArguments.put(jvm.org.dmg.pmml.FieldName.create(k), v)
```

Doesn't matter if one is using Py4J or (Py)jnius backend, there will be ~ten round-trips involved when preparing each data record. At minimum, the JPMML-Evaluator library should provide a method for encoding/decosing all map keys between `java.lang.String` and `org.dmg.pmml.FieldName` types.

**Comment by vruusmann** [comment]
One argument in favour of keeping the existing Py4J integration - I'd like to reuse the JPMML-Evaluator-Python package in other Python packages, specifically in the upcoming JPMML-Evaluator-PySpark package.

PySpark already has a Py4J backend configured and readily accessible.

**Comment by AbdealiLoKo** [comment]
I think having both py4j and jnius makes sense if the maintenance overhead seems reasonable to you.
I can see the benefit of having the py4j for spark, while I am not very sure whether the JVM from spark can be reused by the library as it may cause issues with the functions that the JVM is supposed to perform like the communications, heartbeats etc (it may need to spawn another JVM probably for this processing).

I'm not super knowledgable about it - but for what it's worth ... I've used pyjnius inside a PySpark UDF successfully.

**Comment by vruusmann** [comment]
> I'd like to reuse the JPMML-Evaluator-Python package .. in the upcoming JPMML-Evaluator-PySpark package.

This comment was made with this issue in mind:
https://github.com/jpmml/jpmml-evaluator-spark/issues/21

**Comment by vruusmann** [comment]
My private PyJNIus integration goes nicely until I hit this line:
```python
javaResults = self.javaEvaluator.evaluate(javaArguments)
```

And I get stuck for real here. The problem is that Java class `org.jpmml.evaluator.ModelEvaluator` has two methods with the name "evaluate" (`evaluate(Map)` and `evaluate(EvaluationContext)`). PyJNIus really doesn't know which one to use, and returns the last one as a default.

I can't find a way to instruct PyJNIus to use the first one. Looks like PyJNIus support is impossible without JPMML-Evaluator library change first (need to rename the second evaluate method).

**Comment by vruusmann** [comment]
@AbdealiJK Your code works around this method resolution issue by instantiating a `ModelEvaluationContext` object directly, and then invoking its `declare(FieldName, Object)` method.

However, this approach does not work with `MiningModel` elements (should be instantiating a `MiningModelEvaluationContext` in that case), and bypasses all input value sanity checks (the declare method is private API, only to be called with properly prepared field values).

**Comment by AbdealiLoKo** [comment]
I see, wasn't aware of that - just got it working by looking through the code :)
Something sounds unusual about the "evaluate" not working for two methods with different signatures ... Cause things like `System.out.println` and others seem to work fine
Also, test cases seem to exist - https://github.com/kivy/pyjnius/blob/master/tests/java-src/org/jnius/MultipleMethods.java

https://github.com/kivy/pyjnius/issues/328 This seems to be a related issue.
Note also, that I had an issue with giving `None` values into PMML and was fixed in jinus in `master` - https://github.com/kivy/pyjnius/issues/385

The [JavaMultipleMethod](https://pyjnius.readthedocs.io/en/stable/api.html#jnius.JavaMultipleMethod) api method may help in explicitly telling jnius that there are two different functions with different signatures ?
CC @KeyWeeUsr if available to help

**Comment by vruusmann** [comment]
Updated documentation about PyJNIus vs. Py4J backend options.

**Comment by AbdealiLoKo** [comment]
@vruusmann That is pretty neat - The structure of the package is pretty modular and this is quite awesome.
 I'm curious - Was unable to understand how you overcame the `evaluate()` overloading issue mentioned above ? Can't see anything specific to it in the commit

**Comment by vruusmann** [comment]
> Was unable to understand how you overcame the evaluate() overloading issue mentioned above?

I simply decided to rename the `org.jpmml.evaluator.ModelEvaluator#evaluate(ModelEvaluationContext)` to `#evaluateInternal(ModelEvaluationContext)`. Please note that this rename breaks your existing Python package!

Technically, I updated the parent POM from `org.jpmml:jpmml-evaluator:1.4.6` to `1.4-SNAPSHOT`. This newly built library JAR file is available in the resources subdirectory. Will move back to a stable base version once the JPMML-Evaluator library version 1.4.7 has been prepared and released.

**Comment by AbdealiLoKo** [comment]
Got it :+1:
I should move to using the public API too - will do so. Thanks for the heads up
