### ISSUE TITLE
Is there a way to turn off  `too many input fields` exception?

### ISSUE THREAD

**Issue by shunchi99** [jpmml/jpmml-evaluator-python#13]
I have a model with ~3,000 signals. When I try to load the model, it returns this error. 
`JavaException: JVM exception occurred: Model has too many input fields org.jpmml.evaluator.InvalidElementException`
Is there a way to get around this?

Thanks,
shun

**Comment by vruusmann** [comment]
> I have a model with ~3,000 signals.

Is this model based on structured data (eg. 3000 database columns), or unstructured data (eg. 3000 pixels)?

The current limit of 1000 input fields reflects my understanding about how a "normal structured data model" should look like. But I'm open for enlightenment.

> JavaException: JVM exception occurred: Model has too many input fields org.jpmml.evaluator.InvalidElementException
>
> Is there a way to get around this?

You can disable this check in the Java/JVM language environment by overriding the `ModelEvaluatorBuilder#checkSchema(ModelEvaluator<?>)` method with custom business logic:

```
Evaluator evaluator = new LoadingModelEvaluatorBuilder(){

  @Override
  public void checkSchema(ModelEvaluator<?> modelEvaluator){
    // Do nothing - all model configs are acceptable
  }
}
  .load(new File(..))
  .build();
```

However, such direct subclassing is currently not possible via the Python wrapper.

**Comment by vruusmann** [comment]
The Python-based `ModelEvaluatorBuilder` class could introduce builder methods for configuring input field count thresholds, or for disabling this input field count check altogether.

Would be a temporary API, which gets replaced/removed once there's a better solution available.

**Comment by shunchi99** [comment]
@vruusmann  Thank you very much for your quick reply. Yes, it is based on tabular data with ~3000 different types of signals. The model was trained by spark and that is why we can handle such many signals.

If there is a method to change the thresholds easily, it would much helpful. 
I believe, with distributed training on GBDT, 1000 limit may be a bit too constrained.

**Comment by shunchi99** [comment]
> The Python-based `ModelEvaluatorBuilder` class could introduce builder methods for configuring input field count thresholds, or for disabling this input field count check altogether.
> 
> Would be a temporary API, which gets replaced/removed once there's a better solution available.

Just to confirm, will this be implemented in the short future or it has been implemented and I can use it now?x

**Comment by vruusmann** [comment]
> Just to confirm, will this be implemented in the short future

I'll implement some workaround within the next 24 hours.

You shall receive a GitHub notification when the fixing commit gets pushed to here. I assume that the fixed JPMML-Evaluator-Python package version should then be released to PyPI as well, no?

**Comment by vruusmann** [comment]
The workaround was implemented in the form of "lax" parameter to model evaluator builder classes.

Strict mode (is default):
```python
evaluator_builder = LoadingModelEvaluatorBuilder(lax = False)
```

Lax mode:
```python
evaluator_builder = LoadingModelEvaluatorBuilder(lax = True)
```

The "lax" parameter was also added to the `make_evaluator` utility function.
