### ISSUE TITLE
How to handle NaN fields

### ISSUE THREAD

**Issue by shunchi99** [jpmml/jpmml-evaluator-python#15]
In my data, there are many `NaN` fields. when I try to use the evaluator on a dataframe
```
results_df = evaluator.evaluateAll(df)
print(results_df)
```
I got the following error.
`JavaException: JVM exception occurred: Field "abc" cannot accept user input value NaN org.jpmml.evaluator.InvalidResultException`

How should I handle NaN fields?

**Comment by vruusmann** [comment]
> JavaException: JVM exception occurred: Field "abc" cannot accept user input value NaN org.jpmml.evaluator.InvalidResultException

The PMML specification states that `NaN` (Not-a-Number) values must be regarded as invalid values. This is in stark contrast with Scikit-Learn (and other Python-based ML frameworks), which use `NaN` for signalling a missing value.

So, this `JavaException` means that you're attempting to pass an invalid input value to a model, but the model is not allwed to accept it.

> How should I handle NaN fields?

Replace all `NaN` values with Python `None` values.

Alternatively, you could tweak the model schema definition inside the PMML document, and stipulate that "all invalid values should be automatically converted to missing values".
See http://dmg.org/pmml/v4-3/MiningSchema.html#xsdType_INVALID-VALUE-TREATMENT-METHOD

```xml
<MiningSchema>
  <MiningField name="x" invalidValueTreatment="asMissing"/>
</MiningSchema>
```

The above `MiningField@invalidValueTreatment` attribute would allow the model to accept invalid values (such as `NaN`).

**Comment by vruusmann** [comment]
In my internal TODO file I have the following feature idea that `evaluate` and `evaluateAll` methods should accept a boolean parameter `nan_as_missing` (should be `True` by default?).
