### ISSUE TITLE
Convert PMML serialized model to Sklearn

### ISSUE THREAD

**Issue by sashankchittoory** [jpmml/jpmml-evaluator-python#24]
Hi Team

Is it possilbe to convert PMML serialized model to scikit-learn model instance using jpmml-evaluator-python library

**Comment by vruusmann** [comment]
> Is it possilbe to convert PMML serialized model to scikit-learn model instance ...

See this project instead: https://github.com/iamDecode/sklearn-pmml-model

> .. using jpmml-evaluator-python library

The JPMML-Evaluator-Python package provides PMML-based prediction services for the Python language environment. It does not have any ambitions beyond that.

**Comment by sashankchittoory** [comment]
Thanks for the reply ..
