### ISSUE TITLE
Replace numpy.NaN with numpy.nan

### ISSUE THREAD

**Issue by jihaekor** [jpmml/jpmml-evaluator-python#25]
With the NumPy 2.0 release, `np.NaN` was removed and `np.nan` should be used instead. Because of this, I am getting the following error in the `evaluateAll` call:

```
AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
```

Below is the output from a `ruff` check using `NPY201` according to the migration guide:

```
jpmml_evaluator/__init__.py:19:40: NPY201 [*] `np.NaN` will be removed in NumPy 2.0. Use `numpy.nan` instead.
   |
17 | def _canonicalizeAll(arguments_df, nan_as_missing):
18 |     if nan_as_missing:
19 |         arguments_df = arguments_df.replace({numpy.NaN: None})
   |                                              ^^^^^^^^^ NPY201
20 |     return arguments_df
   |
   = help: Replace with `numpy.nan`

jpmml_evaluator/tests/test_data.py:14:10: NPY201 [*] `np.NaN` will be removed in NumPy 2.0. Use `numpy.nan` instead.
   |
12 |         arguments = {
13 |             "A" : int(1),
14 |             "B" : numpy.NaN,
   |                   ^^^^^^^^^ NPY201
15 |             "C" : str("3")
16 |         }
   |
   = help: Replace with `numpy.nan`

jpmml_evaluator/tests/test_data.py:24:40: NPY201 [*] `np.NaN` will be removed in NumPy 2.0. Use `numpy.nan` instead.
   |
23 |     def test_canonicalizeAll(self):
24 |         arguments_df = DataFrame([[int(1)], [numpy.NaN], [str("3")]], columns = ["X"])
   |                                              ^^^^^^^^^ NPY201
25 |         self.assertEqual(object, arguments_df["X"].dtype)
26 |         arguments_df = _canonicalizeAll(arguments_df, nan_as_missing = True)
   |
   = help: Replace with `numpy.nan`

Found 3 errors.
[*] 3 fixable with the `--fix` option.
```

Would it be possible to get this updated?

**Comment by vruusmann** [comment]
> With the NumPy 2.0 release, np.NaN was removed and np.nan should be used instead.

The JPMMl-Evaluator-Python package depends on a higher-level Pandas package (eg. `from pandas import DataFrame`), not the low(est)-level Numpy package. And as much as I have tested, Pandas 2.2.2 (the latest in PyPI currently) does not work with Numpy 2.0.X.

Of course, this does not mean that one couldn't standardize the representation of Numpy constants in the meantime.

**Comment by jihaekor** [comment]
> And as much as I have tested, Pandas 2.2.2 (the latest in PyPI currently) does not work with Numpy 2.0.X.

This is inconsistent with regards to my work (I am using the latest version of `pandas` just fine with `numpy` 2.0 in the codebase for which I have tested), along with what is stated in the `pandas` documentation here:
https://pandas.pydata.org/docs/whatsnew/v2.2.2.html#pandas-2-2-2-is-now-compatible-with-numpy-2-0

It looks like `pandas` v2.2.2 does have support for `numpy` 2.0, and as such, they also do not pin `numpy` requirements in their project.

Also, to your point, given that those are just constant representations, it probably is worth updating anyways to the newest convention adopted.

**Comment by jihaekor** [comment]
@vruusmann Thank you for the fix and update!
