### ISSUE TITLE
Using Python equivalent of the basic usage of jpmml-evaluator from Java 

### ISSUE THREAD

**Issue by pwittchen** [jpmml/jpmml-evaluator-python#6]
Here's an example of basic usage of jpmml-evaluator for Java: https://github.com/jpmml/jpmml-evaluator#basic-usage. 
How can I write equivalent code in Python?

Especially this part:

```java
	Map<String, ?> inputRecord = readRecord();
	if(inputRecord == null){
		break;
	}

	Map<FieldName, FieldValue> arguments = new LinkedHashMap<>();

	// Mapping the record field-by-field from data source schema to PMML schema
	for(InputField inputField : inputFields){
		FieldName inputName = inputField.getName();

		Object rawValue = inputRecord.get(inputName.getValue());

		// Transforming an arbitrary user-supplied value to a known-good PMML value
		FieldValue inputValue = inputField.prepare(rawValue);

		arguments.put(inputName, inputValue);
	}

	// Evaluating the model with known-good arguments
	Map<FieldName, ?> results = evaluator.evaluate(arguments);
```

in order to create `arguments` map or dictionary in case of Python. I couldn't find anything like this in the documentation.

**Comment by vruusmann** [comment]
This particular code snippet demonstrates how to prepare field values for evaluation one-by-one. The idea is that if some user input value is invalid (eg. previously unseen category level), then you can catch the corresponding `PMMLException` or `IllegalArgumentException` and perform very fine-grained error reporting.

However, in most application scenarios, fields are prepared in one go, simply by mapping Python values to Java values. See the `jpmml_evaluator.JavaBackend.dict2map(dict)` and `jpmml_evaluator.JavaBackend.map2dict(map)` methods:
https://github.com/jpmml/jpmml-evaluator-python/blob/0.3.1/jpmml_evaluator/__init__.py#L15-L19

If you really need to prepare field values one-by-one in Python, then you'd need to adapt the above methods for your needs - there's noting more detailed available. Please remember that Java-Python-Java roundtrips are quite expensive, so it might be worthwhile to implement some helper utility function in Java (contains all exception handling logic), and call it once from Python for each scorable data record.

**Comment by pwittchen** [comment]
Thanks for the detailed comment.
