### ISSUE TITLE
Getting subprocess.CalledProcessError: Command '['which', 'javac']' returned non-zero exit status 1 when calling make_evaluator with jnius

### ISSUE THREAD

**Issue by pwittchen** [jpmml/jpmml-evaluator-python#7]
Hi,

I have the following problem.

Here's my code:

```python
        jnius_configure_classpath(user_classpath=[
            get_project_root_dir() + '/sklearn2pmml_config/',
            get_project_root_dir() + '/sklearn2pmml_plugin/target/plugin-1.0-SNAPSHOT.jar']
        )

        backend = PyJNIusBackend()

        evaluator = make_evaluator(backend, pmml_file_path).verify()
        inputs = backend.map2dict(input_data)
        results = evaluator.evaluate(inputs)
```

It throws an error:

```
subprocess.CalledProcessError: Command '['which', 'javac']' returned non-zero exit status 1.
```

during `make_evaluator(...)` invocation.

Complete stacktrace is provided below.

I debugged this code and I've noticed that error occurs in `pyjnius.py` file on line 15 in `newObject` function when calling `from jnius import autoclass`.

When I type `echo $JAVA_HOME`, I have the following output:

```
//home/piotrwittchen/.sdkman/candidates/java/current
```

current links to `//home/piotrwittchen/.sdkman/candidates/java/8.0.252-zulu`

When I type `whereis javac`, I have the following output:

```
javac: /home/piotrwittchen/.sdkman/candidates/java/8.0.252-zulu/bin/javac
```

I have no idea what can be wrong in my setup.

When I enter `python` and type:

```
>>> from jnius import autoclass
```

then I don't get any errors and I can perform simple hello world example without problems:

```
>>> autoclass('java.lang.System').out.println('Hello world')
```

It seems that there's an issue related to pyjnius integration inside jpmml-evaluator-python.

My stacktrace:

```
File "/home/piotrwittchen/.virtualenvs/vodka/lib/python3.6/site-packages/jpmml_evaluator/__init__.py", line 149, in make_evaluator
    evaluatorBuilder = LoadingModelEvaluatorBuilder(backend) \
  File "/home/piotrwittchen/.virtualenvs/vodka/lib/python3.6/site-packages/jpmml_evaluator/__init__.py", line 119, in __init__
    javaModelEvaluatorBuilder = backend.newObject("org.jpmml.evaluator.LoadingModelEvaluatorBuilder")
  File "/home/piotrwittchen/.virtualenvs/vodka/lib/python3.6/site-packages/jpmml_evaluator/pyjnius.py", line 15, in newObject
    from jnius import autoclass
  File "/home/piotrwittchen/.virtualenvs/vodka/lib/python3.6/site-packages/jnius/__init__.py", line 42, in <module>
    from .reflect import *  # noqa
  File "/home/piotrwittchen/.virtualenvs/vodka/lib/python3.6/site-packages/jnius/reflect.py", line 20, in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
  File "/home/piotrwittchen/.virtualenvs/vodka/lib/python3.6/site-packages/six.py", line 856, in __new__
    return meta(name, resolved_bases, d)
  File "jnius/jnius_export_class.pxi", line 119, in jnius.MetaJavaClass.__new__
  File "jnius/jnius_export_class.pxi", line 179, in jnius.MetaJavaClass.resolve_class
  File "jnius/jnius_env.pxi", line 11, in jnius.get_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 134, in jnius.get_platform_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 84, in jnius.create_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 47, in jnius.find_java_home
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['which', 'javac']' returned non-zero exit status 1.
```

**Comment by vruusmann** [comment]
It looks like a JDK vs. JRE issue, because the `which` command is looking for the Java compiler (`javac`), not a Java executable (`java`).

What's your target Java version, 1.8? I find it odd that it identifies itself as `java-8.0` and not as `java-1.8`. Perhaps PyJNIus is also expecting to find substring `1.8` (`1.7`, `1.8` vs `9.0`, `10.0`, `11.0` etc.).

Or maybe it's a factor that your `JAVA_HOME` environment variable starts with two backslashes (would expect one there).

> When I type whereis javac

What happens if you type `which javac` - exactly what the PyJNIus package is doing?

> When I enter python and type `from jnius import autoclass` then I don't get any errors

What happens if you do `jnius_configure_classpath()` without your custom `user_classpath`? Perhaps your custom SkLearn2PMML-enhanched user classpath is somehow at fault here?

> It seems that there's an issue related to pyjnius integration inside jpmml-evaluator-python.

I think it's 100% PyJNIus issue (not JPMML-Evaluator-Python issue), and you should ask that community for more advice/insight.

Have you tried running JPMML-Evaluator-Python unit tests?
```
$ cd jpmml-evaluator-python
$ nosetests
```

Passes cleanly on my computer.

And you can always fall back to Py4J backend.

**Comment by pwittchen** [comment]
Thanks for the response.

When I type `which javac` it shows my location of the `javac` in `$JAVA_HOME/bin` directory. I already checked that earlier.
I tried Py4J backend and also had some issues.

I abandoned this path and decided to use jpmml-evaluator written in java with py4j as a separate, standalone java app and then connected to it via py4j in the python app. It's similar concept like jpmml-evalutator-python, but done without this python library. This approach allowed me to perform more customizations in the evaluator java app. I haven't finished my app yet, but I already see that loading PMML model works and I need to add prediction to have complete solution. I think that's probably the best idea in my case.

**Comment by vruusmann** [comment]
> I tried Py4J backend and also had some issues.

Could you run `nosetests`, and open a GitHub issue for each problem?

There should be exactly two unit tests run, one with PyJNIus backend and another one with Py4J backend. As mentioned earlier, everything works fine on my computer (Java 1.8 on GNU/Linux), so I'm blissfully unaware of other peoples' struggles with JPMML-Evaluator-Python.

**Comment by pwittchen** [comment]
I cloned this repo.

When I run `nosetests` I get:

```
Traceback (most recent call last):
  File "/usr/sbin/nosetests", line 5, in <module>
    from nose import run_exit
ModuleNotFoundError: No module named 'nose'
```

I don't know why. I have `nose` package installed. I also tried to run it form `jpmml_evaluator` dir and in virtualenv.

Source of my `/usr/sbin/nosetests` file looks like this:

```python
#!/usr/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from nose import run_exit
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(run_exit())
```

Moreover, nose works with my other projects in virtualenv.

**Comment by pwittchen** [comment]
Ok, I made it work. I removed `/usr/sbin/nosetests` file and installed nose in virtualenv. I also installed all dependencies and executed tests. Both tests are passing.

**Comment by vruusmann** [comment]
> Both tests are passing.

Still using the same Java 8.0_252-zulu?

In that case, there must be something wrong with your `jnius_configure_classpath` function call.

**Comment by pwittchen** [comment]
Yes, I debugged it and error was thrown by this method, but it happened inside jnius - not jpmml-evaluator-python.
